### ISSUE TITLE
Bug: Panic in style rules

### ISSUE THREAD

**Issue by bryceberger** [dalance/svlint#211] opened 2022-12-08 00:28 UTC
Writing testbenches, I came across a panic that crashes svls (0.2.6). Traced it to the style rules of svlint (0.6.0). This happens in at least the following style rules (the only ones I had enabled):
```
style_keyword_1space = true
style_keyword_0or1space = true
style_keyword_construct = true
style_keyword_end = true
style_keyword_newline = true
```
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/svlint-0.6.0/src/rules/style_keyword_0or1space.rs:53:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/02654a0844f5c8d29bac318c3c6c666da3d8543d/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/02654a0844f5c8d29bac318c3c6c666da3d8543d/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/02654a0844f5c8d29bac318c3c6c666da3d8543d/library/core/src/panicking.rs:48:5
   3: <svlint::rules::style_keyword_0or1space::StyleKeyword0Or1Space as svlint::linter::Rule>::check
   4: svlint::linter::Linter::check
   5: svls::backend::Backend::lint
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
   9: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
  11: <core::pin::Pin<P> as core::future::future::Future>::poll
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  14: futures_util::stream::stream::StreamExt::poll_next_unpin
  15: <futures_util::stream::stream::buffer_unordered::BufferUnordered<St> as futures_core::stream::Stream>::poll_next
  16: <futures_util::stream::stream::filter_map::FilterMap<St,Fut,F> as futures_core::stream::Stream>::poll_next
  17: <futures_util::stream::stream::Forward<St,Si> as core::future::future::Future>::poll
  18: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: tokio::runtime::scheduler::current_thread::Context::enter
  22: tokio::macros::scoped_tls::ScopedKey<T>::set
  23: tokio::runtime::scheduler::current_thread::CurrentThread::block_on
  24: tokio::runtime::runtime::Runtime::block_on
  25: svls::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The issue occurs in `tb_ahb_slave.sv`, but not `tb_data_buffer.sv`, with the given `.svlint.toml`.
[issue.zip](https://github.com/dalance/svlint/files/10181118/issue.zip)

**Comment by DaveMcEwan** [comment] 2022-12-08 11:53
I'm not able to reproduce the stacktrace with svlint.
- The file `tb_data_buffer.sv` has a syntax error on line 57 (`endfunction` instead of `endtask`).
- The file `tb_ahb_slave.sv` does not preprocess because it can't find `sources/states.sv`.

@bryceberger Would you mind trying with those issues fixed and see if you still get a crash?

**Comment by DaveMcEwan** [comment] 2022-12-08 11:58
Actually, hang on. I can fix those myself and reproduce the problem now.

**Comment by bryceberger** [comment] 2022-12-09 10:14
Yep, that appears to have done it!

**Comment by DaveMcEwan** [comment] 2022-12-18 18:03
@bryceberger There's a new released version (v0.6.1) which includes the fix. If you're happy with this, would you close this issue?

**Closed** 2022-12-20 02:14 UTC
